// -*- coding: utf-8 -*-
// Project    : ShanYanDemo
// File       : AppConfig.ets
// Time       ：2024/10/29
// Author     ：ya dong
// Copyright © 2024 CL. All rights reserved.

export default class AppConfig {
  static readonly APP_ID: string = 'F6lfp6m4'
  static readonly APP_KEY: string = ''
  static readonly URL_MobileQuery: string = 'https://api.253.com/open/flashsdk/mobile-query'
  static readonly URL_MobileValidate: string = 'https://api.253.com/open/flashsdk/mobile-validate'
}

